# Default values are available here: https://github.com/bitnami/charts/blob/master/bitnami/external-dns/values.yaml

external-dns:
  provider: aws
  namespace: external-dns

  serviceAccount:
    annotations:
      # âš ï¸ Change this ğŸ‘‡
      eks.amazonaws.com/role-arn: arn:aws:iam::969990446292:role/external-dns
